# Langue du plugin (le fichier sera généré dans le dossier /lang/)
language: "fr"

# Configuration du GUI des outils
menus:
  tools:
    title: "<dark_aqua>Menu des Outils Evolutifs"
    size: 3

messages_action_barre: true

# Paramètres globaux
settings:
  level_up_sound: "ENTITY_PLAYER_LEVELUP"
  level_up_volume: 1.0
  level_up_pitch: 1.0
  use_vault: true
